### ISSUE TITLE
Hue Service crashing with error message on Vero4K+

### ISSUE THREAD

**Issue by Arnoud6432** [zim514/script.service.hue#144]
**Describe the bug**
When the service is started, an error message appears with text "local variable 'error' referenced before assignment"

**To Reproduce**
1. Using Kodi Matrix 19.1 on a OSMC Vero 4K+ device
2. Install Hue Service add-on version 1.1.1 (I installed using zip file option)
3. After installation, a popup will appear saying "Bidge not configured"
4. An error message dialog box appears with message "local variable 'error' referenced before assignment"

**Expected behavior**
I expected the add-on to start without error messages and be working.

**Screenshots**

**System (please complete the following information):**
- OS: OSMC Kodi Matrix 19.1 using the standard skin, running on Linux 4.9.113-45-osmc aarch64

**Additional context**
I also tried 0.14.0.dev1. Tried uninstalling the addon including its settings and reinstalling. Same error. Error also appears directly after rebooting the Vero4K. I can get into the configure screen, it will detect my bridge and I'm able to choose scenes. But when I try to save the settings, the error message appears again and the settings are not saved.

**Comment by zim514** [comment]
Thanks for reporting this crash in the app. I've been seeing it a lot and it appears to be in script.module.simplecache.

Could you please try deleting simplecache.db in  [Userdata](https://kodi.wiki/view/Userdata)\addon_data\script.module.simplecache and trying again?

[UnboundLocalError: local variable 'error' referenced before assignment #19](https://github.com/kodi-community-addons/script.module.simplecache/issues/19)

`File /home/osmc/.kodi/addons/script.module.simplecache/lib/simplecache.py line 67 in get
result = self._get_db_cache(endpoint, checksum, cur_time, json_data)
File /home/osmc/.kodi/addons/script.module.simplecache/lib/simplecache.py line 136 in _get_db_cache
cache_data = self._execute_sql(query, (endpoint,))
File /home/osmc/.kodi/addons/script.module.simplecache/lib/simplecache.py line 252 in _execute_sql args locals
self._log_msg("_database ERROR ! -- %s" % str(error), xbmc.LOGWARNING)`

**Comment by Arnoud6432** [comment]
Thanks for the quick reply. The fix is working!

1. Deleted file :~/.kodi/userdata/addon_data/script.module.simplecache/simplecache.db
2. Reboot Vero4K
3. Did not get error message at startup
4. Was able to configure scenes and settings without error message, settings were correctly saved
5. Lights are turning on and off correctly as per my settings
