### ISSUE TITLE
 Unknown colour gamut for light -1 during Startup/Settings Menu

### ISSUE THREAD

**Issue by dolorosus** [zim514/script.service.hue#170]
**Describe the bug**
During startup a message:  "Unknown colour gamut for light -1" is shown.

**To Reproduce**
Steps to reproduce the behaviour:
1. startup Kodi or activate the add-on

The same message appears if I try to set a scene name for Play/Pause/Stop. After the message appears I' thrown out of the settings menu

**Expected behaviour**
No message! 
 (As it was before updated to 1.1.13) unfortunately I can't remember which version was ok.
**Screenshots**

**System (please complete the following information):**
 - OS: Android 9
 - System Version 9
 - Kodi Version 19.3

![grafik](https://user-images.githubusercontent.com/11487796/167301372-b3907102-695d-4b66-ae17-ac99151ab8be.png)

**Comment by zim514** [comment]
Could you please run kodi in debug mode and provide logs? You can find information on how to do this here: https://kodi.wiki/view/Log_file/Easy

Also, are you using any "unofficial" bulbs from other manufacturers?

**Comment by zim514** [comment]
I was able to reproduce the problem, it occurs only if you have no ambilights selected, even if ambilight is set to off.

**Comment by zim514** [comment]
Should be fixed in v1.1.8 and higher, available on the releases page or dev repo.

**Comment by dolorosus** [comment]
Thanks a lot for immediate fixing!
