### ISSUE TITLE
Make compatible with diyHue

### ISSUE THREAD

**Issue by jclsn** [zim514/script.service.hue#172]
**Is your feature request related to a problem? Please describe.**
It doesn't find the diyHue bridge, which is found by the official Hue app.

https://diyhue.github.io/

I also can't type an IP. It would be great to be able to connect to this application. It would provide the ability to use cheaper lights than Philips Hues.

**Comment by zim514** [comment]
Is this the error you're getting: `JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

If not, please let me know what it is and [provide Kodi logs](https://kodi.wiki/view/Log_file/Easy), and make sure to select 'yes' when asked to report errors.

I don't know anything about diyHue so can't say if it's possible yet but I can investigate

**Comment by jclsn** [comment]
Yes, either that error or bridge not found.

DiyHue basically emulates a Hue bridge on e.g. a Raspberry Pi. I could get it to connect to Home Assistant and now only need this to sync.

**Comment by zim514** [comment]
Ok, I've tried to make that type of discovery work in the past but wasn't able. Entering the IP manually won't work right now but I'll make the changes in a future version

**Comment by jclsn** [comment]
You could contact the diyHue team and ask what you would need to discover.

**Comment by zim514** [comment]
The best solution will be to add manual IP entry as an option if the current discovery doesn't work, which should address both this and #173

**Comment by zim514** [comment]
Please try this version https://github.com/zim514/script.service.hue/releases/tag/v1.2-dev1

**Comment by jclsn** [comment]
Yes, I could connect now and see the lights, but they don't react. I am also using Hyperion by now, which supports my whole TV and not only Kodi. They also have problems when using the Hue Entertainment API of diyHue instead of the older API. Do you use that as well?

**Comment by zim514** [comment]
ambilight doesn't work on all hardware so it's possible that's what you're running into. It's a Kodi limitation and not something I can fix unfortunately. What kind of device are you running Kodi on? It doesn't work on RPi, Android or AmLogic devices, possibly others

**Comment by jclsn** [comment]
Ah okay. Yeah it is a Pi
