### ISSUE TITLE
Bridge not found and unable to enter IP manually

### ISSUE THREAD

**Issue by rgnjwrgjlnrb** [zim514/script.service.hue#173]
After installing the add-on It is not able to find the hue bridge. The bridge is connected to a second local LAN (different eth interface) with no internet connection. Suspecting that the add-on would only try to find the bridge over one interface I have disabled all interfaces except the one connected directly to the hue bridge, but the add-on is still unable to find it. The setup is like this: Kodi eth1 10.0.0.1 <----> hue bridge 10.0.0.2 I'm not able to enter the bridge IP (10.0.0.2) manually either.

- Is it possible to configure the hue bridge IP manually, editing a config file?
- Can the add-on be fixed to find hue bridges connected to the LAN (but without internet)
- Can the add-on be fixed to allow entering the bridge IP manually on the add-con config?

Thanks!

**Comment by rgnjwrgjlnrb** [comment]
After installing the add-on It is not able to find the hue bridge. The bridge is connected to a second local LAN (different eth interface) with no internet connection. Suspecting that the add-on would only try to find the bridge over one interface I have disabled all interfaces except the one connected directly to the hue bridge, but the add-on is still unable to find it. The setup is like this: Kodi eth1 10.0.0.1 <----> hue bridge 10.0.0.2 I'm not able to enter the bridge IP (10.0.0.2) manually either.

- Is it possible to configure the hue bridge IP manually, editing a config file?
- Can the add-on be fixed to find hue bridges connected to the LAN (but without internet)
- Can the add-on be fixed to allow entering the bridge IP manually on the add-con config?

Thanks!

**Comment by zim514** [comment]
Hi

You can manually edit the settings.xml in [userdata](https://kodi.wiki/view/Userdata)/addon_data/script.service.hue but also need to manually create a user on the bridge for it to work...

I'm working on allowing manual IP entry as a fallback in the current discovery flow to solve both this and  #172, it should be in the next available version.

**Comment by zim514** [comment]
Please try this version https://github.com/zim514/script.service.hue/releases/tag/v1.2-dev1

**Comment by rgnjwrgjlnrb** [comment]
thanks. after seeing #147 (only one ambilight color with this add-on) i'll try to get the add-on script.kodi.hue.ambilight working first before i try this one. for those having the same problem, if you want  to configure it manually it is very easy to create a user  on the hue bridge with curl:

$ curl -d '{"devicetype":"$DEVICE-NAME"}' -H "Content-Type: application/json" -X POST 'http://$BRIDGE-IP/api'
response:
[{"error":{"type":101,"address":"","description":"link button not pressed"}}]

now press the button on the hue bridge and repeat:

$ curl -d '{"devicetype":"$DEVICE-NAME"}' -H "Content-Type: application/json" -X POST 'http://$BRIDGE-IP/api' ; echo
response:
[{"success":{"username":"XXXXXXXXXXXXXXXXXX"}}]

$DEVICE-NAME can be any any string, for example "Kodi"
$BRIDGE-IP is the IP of the hue bridge, for example 192.168.0.9
XXXXXXXXXXXXXXXXXXX is the username/key you have created (alphanumeric string)

**Comment by kodiuser12345** [comment]
I have the same problem, I can't enter the IP manually, I tried the last version from https://github.com/zim514/script.service.hue/releases/tag/v1.12.14 and I also tried https://github.com/zim514/script.service.hue/releases/tag/v1.2-dev1. There is no way to enter the IP like with other programs, just an error it can't find the bridge. 

If I look the setting file ./.kodi/addons/script.service.hue/resources/settings.xml there is setting id="bridgeIP" and setting id="bridgeUser" but I don't understand the syntax to put the IP and hue user/key there. Should I put these with the <data> and </data> tags and should I remove anything from the section? It is really painful to make this work!

**Comment by zim514** [comment]
Could you please provide debug logs?

**Comment by kodiuser12345** [comment]
Has manual entry of bridge IP been implemented? If not, how could debug logs be useful at all? I only see I can't enter the IP, maybe I'm doing something wrong and maybe it's not implemented yet. But I don't get any errors that could make reading logs be useful. I just want to clarify before uploading them...

**Comment by zim514** [comment]
Yep, if you select 'Discover bridge' but it doesn't find one, it _should_ prompt you to enter an IP manually and then continue the connection flow. If you're not getting the prompt, logs will help me figure out why

**Comment by kodiuser12345** [comment]
Thanks for the clarification! Logs attached (username replaced with $user), it complains about a missing module called PIL, maybe that is the reason

[hue-logs.txt](https://github.com/zim514/script.service.hue/files/9378010/hue-logs.txt)

**Comment by zim514** [comment]
Probably. PIL is included with Kodi, you may have to reinstall Kodi to fix the problem. What OS are you running Kodi on?

**Comment by kodiuser12345** [comment]
I use Linux, Kodi comes in a package. If I remove and add it again I'll end up with the same files. There is an optional package with Kodi binary add-ons, but I have no idea if PIL is included with the Kodi package or not or how to check. Is there a file I should be looking for? Maybe it was compiled without PIL. I actually have no idea what PIL is..

**Comment by zim514** [comment]
PIL is the Python Imaging Library / Pillow python package. It comes bundled with Kodi so I'm not sure why it wouldn't be included in your install. It _may_ be part of the binary add-ons but I'm not sure. I think you can also try 'pip install Pillow' from the command line to install it manually. It's a problem with the Kodi installation rather than the Hue add-on so I'm sure how to fix it. You may have better luck asking on https://forum.kodi.tv/
