### ISSUE TITLE
Discover does not work with manual ip

### ISSUE THREAD

**Issue by SecretUnicorn** [zim514/script.service.hue#202]
I added the bridge ip in the config and it shows up in kodi. Now when I try to select a scene it says that no bridge is configured. Discover Hue Bridge results in bridge not found. Ip is correct though...

**Comment by zim514** [comment]
I'll need debug logs to look into this. You can find methods for getting logs from Kodi [here.](https://kodi.wiki/view/Log_file/Easy)
