### ISSUE TITLE
Daylight setting no longer working

### ISSUE THREAD

**Issue by SamDW96** [zim514/script.service.hue#242]
Since a few weeks, it seems that the daylight setting has the inverted effect. When the setting is enabled, the lights perform their assigned actions during daylight but don't do anything after sunset.

I am on one of the latest Omega nightlies (for Dolby Vision support) on an NVIDIA Shield Pro.

**Comment by zim514** [comment]
Turning on during daylight should be fixed, but I'm not sure about the second part about them doing nothing after sunset. Can you try the new version on the repo (v.1.4.14), and if that's still happening please provide debug logs

**Comment by SamDW96** [comment]
The new version fixes all issues for me. Thanks a ton for updating, and for notifying me!
