### ISSUE TITLE
Setting any time span disables Hue control

### ISSUE THREAD

**Issue by szotsaki** [zim514/script.service.hue#289]
**Describe the bug**
When I set a time span to enable Hue just for that interval, it disables Hue control completely. If I disable this feature (so Hue control is always enabled, regardless of time), Hue works again.

**To Reproduce**
1. Create two new scenes: "on" and "off" Hue lights
2. Set the scenes the control the lights when the movie paused ("on" for paused, "off" for playing)
3. Enable that Hue control should work only between 18:00 and 06:00.
4. Pause the movie within this interval
5. Hue control is disabled within this interval, the lights won't light up according to the "on" preset
6. Hue control is also disabled when the interval is swapped (06:00 - 18:00)

**Expected behavior**
Hue control works between 18:00 and 06:00

**System (please complete the following information):**
 - OS: SHIELD
 - Kodi Version: 21

**Comment by zim514** [comment]
Are you using [version ](https://github.com/zim514/script.service.hue/releases)2.0.8 of the addon?

**Comment by szotsaki** [comment]
I checked it and it says it's version 1.4.18; last updated: 2024-03-13.

I installed it from the official Kodi addons repo (without adding a new repo manually).

I see that there are a lot of newer versions released here. Is it expected that the Kodi repo version is out of date?

**Comment by zim514** [comment]
The official repo hasn't been updated since there's still a few bugs left. If you get the updated version from the repo it should be much improved, and if you have this bug on that build, I can take a look

**Comment by szotsaki** [comment]
Do you know roughly when you can update it? I assume most of the people who use the Hue add-on, use it from the official repo which also has some bugs.

**Comment by zim514** [comment]
You can follow the pull request for the update [here](https://github.com/xbmc/repo-scripts/pull/2633), but since you didn't test the dev version like I mentioned there's little chance it fixes issues I don't have details about

**Comment by cpu123** [comment]
I auto updated to the latest version and saw that my lights had stopped dimming on playback etc.

A bit of troubleshooting and it seems its to do with the scheduling. My preferred method of operation is to not bother with the schedule/sunrise times etc, and just have it dim the lights if they're on and do nothing if they're off. But if any of these options are selected it seems to not work, if I disable and leave it on the default sunrise settings it works as expected.

**Comment by zim514** [comment]
There were a number of problems in the schedule / override logic that should be fixed in version 2.0.11. You can grab it from the [releases](https://github.com/zim514/script.service.hue/releases) page.
