### ISSUE TITLE
Support for turning all lights off as play action

### ISSUE THREAD

**Issue by SamDW96** [zim514/script.service.hue#294]
Since the rewrite in version 1.5.0, using the Hue API and official scene support, I can no longer make the addon do what I used it for when playing media: turning the lights in the room off entirely. Previously, I could setup a "scene" from within the addon with the lights configured just like this. However, it is not possible to create a scene in the Hue app where all the lights are turned off. At least one light in the room has to be turned on to be able to setup a scene.

I would ask for an option to turn off the lights as a play action, with a configurable transition time as before.

**Comment by zim514** [comment]
I wouldn't have thought of that, thanks for pointing it out. I don't know why the official app doesn't let you do it but one quick work around is to use All4Hue on android, it's a 3rd party app that does let you create an "all lights off" type scene, there are probably other similar apps. I'm not sure I'll have time to add it as a feature but using another app seems to work for me.

**Comment by SamDW96** [comment]
Thank you for your suggestion! This, in turn, is something I hadn't thought of. The Hue Essentials app I already had also allows for scenes with all lights off, so that did the trick.

Thanks for helping out!
