### ISSUE TITLE
Audio play and stop scenes ignored

### ISSUE THREAD

**Issue by NamelessCoder** [zim514/script.service.hue#295]
This is a strange one: regardless of any other settings such as sceduling, sunset consitions, or video scenes/behavior - audio play and stop scenes are completely ignored. The weird part is that the audio *pause* scene is working just fine. Resuming from pause does nothing, nor does stopping from pause. Playing from stopped state does nothing, stopping from playing state does nothing. Have tried different scenes, resetting to defaults - even manually deleting kodi confs and starting over - without success.

Side note: Kodi "forgets" settings after selecting a scene; selecting a scene returns me to the first settings category and unless I switch to the settings category I was in before I click "OK", Kodi does not save the settings of that category. Not sure if related but thought I'd mention it.

**To Reproduce**
1. Select scenes for all audio states
2. Play audio and wait for scene change
3. Pause audio and wait for scene change
4. Resume playback and wait for scene change
5. Stop audio and wait for scene change

**Expected behavior**
All playback states should trigger the configured scene.

**Observed behavior**
Only the pause state scene will trigger. Same happens whether using UI buttons or media shortcuts or web-RPC.

**System (please complete the following information):**
 - OS: LibreELEC
 - System Version: LE 12.0.0 and 12.0.1 (problem was on 11.x too). All versions of Hue Service 2.x.x have had the problem.
 - Kodi Version: 

**Additional context**

**Comment by zim514** [comment]
Thanks for letting me know, I don't really use Kodi for music so this was poorly tested. It should be fixed in 2.0.11, available on the [releases](https://github.com/zim514/script.service.hue/releases) page. 

As for the settings, that's a Kodi limitation. I tried to work around it but didn't really find a way.

**Comment by NamelessCoder** [comment]
Fix is confirmed, thanks for the quick reaction! About the weird settings behavior, I thought as much. Doesn't seem like add-on developers have much control here and I guessed this is just a side effect of making some fields conditional/dynamic. No worries, a few extra clicks don't matter!
