### ISSUE TITLE
Option to turn off all lights on Play action

### ISSUE THREAD

**Issue by slydog3333** [zim514/script.service.hue#298]
I see there was another issue closed with a possible workaround for this since you can't create an all off scene in the hue app(They must figure since you can turn all lights off in their app you don't need it as a scene), but this feature is absolutely needed in this addon. Not being able to have the lights turn off when you start a movie is a critical flaw.

**Comment by slydog3333** [comment]
Looking in to this further for some reason this addon didn't auto update for a year it looks like. Jumping from 1.4.18 to 2.0.10. Just rolling back to the 1.4.18 version and turning off auto updates is the workaround for me. 

I'm still not sure why this essential function was removed.

**Comment by zim514** [comment]
Scene creation functionality exists in may other apps such as All4hue or hue essentials, in a much better way than can be implemented in Kodi. If you'd like to invest your time to develop it, please open a pull request
