### ISSUE TITLE
set positions Hue lamps around the ambilight TV  

### ISSUE THREAD

**Issue by johnfromul** [zim514/script.service.hue#300]
i do not know the grabbing position in my ambilight tv screen, but I have 2 HUE rgb lamps over the left and right top corner and the grabbed color is for both lamp same and i mean, the place of grabbing is too much bottom. Is possible add in the plugin configuration the option with settings for position added HUE lamps in relation to television and maybe set the grabbing frame (or LED points in TV frame)?

<img width="875" alt="image" src="https://github.com/user-attachments/assets/69de85e1-dff1-45cf-ad8b-7757cf7b42e3">

This picture is only for ilustrating of position my add-on HUE lamps (the picture is on my old 65OLED873/12 with native HUE implemetations....now i have 65OLED909 and this model need your plugin)

**Comment by zim514** [comment]
It takes an average of the whole image screen, it's not realistic to make it more precise than that on low powered hardware, you'll have to look into hyperion or prismatik if you want something more sophisticated.
