### ISSUE TITLE
Discover Hue Bridge Button does not work.  

### ISSUE THREAD

**Issue by jbrek** [zim514/script.service.hue#301]
**Describe the bug**
Discover Hue Bridge Button does not work.  
Click it blinks and goes back to add-on information

**System (please complete the following information):**
 - OS: Windows 11 23H2
 - Kodi Version 21

**Additional context**
Hue Service 2.0.12 does not find all scenes.
Hue Service 2.0.12 does not work.  

Everything was working before I got Hue Service warning about Sunset time? 

I have backup of Kodi 20 with Hue Version 1.48 when I select scene I get a list of Ten.   And everything works great!

On Hue Version  2.0.12  I need to select Hue Area, Then scene and I get a list of two.  Where are my other scenes?

**Comment by zim514** [comment]
Old style scenes are no longer supported.
Bridge discovery bug cannot be reproduced. Please include logs if still occuring.
