### ISSUE TITLE
Option to keep lights off

### ISSUE THREAD

**Issue by cyberden** [zim514/script.service.hue#65]
This is not a bug but a feature request. It would be nice to be able to choose wether or not lights should be set to the chosen scene if they were off before.

My use case is when I use my projector, my harmony remote will shut off the lights and then, when I play a file, the addon will switch them on using the "play" scene whereas I would prefer them to stay off. On the contrary, when using my tv, the lights are on before lanching my media and I would like the scene to be applied.

Hope it makes sense; Thanks for your work!

**Comment by zim514** [comment]
see #66

**Comment by zim514** [comment]
Added in version 0.13.0
